---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_zsh: yes
configure_osx: yes

dotfiles_repo: https://github.com/jaredboone/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .zshrc
  - .osx
  - .iterm
  - .terminal
  - .zsh

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - dockutil
  - git
  - gpg
  - node
  - nvm
  - python
  - wget
  - zsh
  - zsh-completions

# Lite
# homebrew_installed_packages:
#   - dockutil
#   - git
#   - node
#   - python
#   - nvm
#   - zsh
#   - zsh-completions

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - appcleaner
  - ccleaner
  - cheatsheet
  - docker
  - firefox
  - github
  - google-chrome
  - inboxer
  - iterm2
  - macpass
  - muzzle
  - slack
  - skype
  - sublime-text
  - visual-studio-code
  - vagrant
  - unlox
  - postman
  - malwarebytes
#  - virtualbox
#  - virtualbox-extension-pack 

# Lite
# homebrew_cask_apps:
#   - iterm2

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1091189122, name: "Bear" }
  - { id: 568494494, name: "Pocket" }
  - { id: 402592703, name: "Time Out" }
  - { id: 1278508951, name: "Trello" }
mas_email: "jared.boone@gmail.com"
mas_password: ""

osx_script: "~/.osx"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
# Broken
  # - name: molecule
  # - name: docker-py

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
