---
- name: Ensure zsh is the user shell.
  shell: sudo dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
  changed_when: false

- name: Ensure zsh is the default shell.
  shell: sudo chsh -s /usr/local/bin/zsh $USER
  changed_when: false
